server:
  port: 8883
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/locals_old?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: sa123
vic:
  database:
    mybatis:
      mapper-scan-path: com.vic.starter.demo.dao